'use client';
import {useState} from 'react';
import Link from 'next/link';
import {UserRound,Building2,CheckCircle2,ArrowLeft} from 'lucide-react';
import {Brand} from '../components/CoreShell';
import {api,message} from '../lib/core';
export default function Cadastro(){
 const [tipo,setTipo]=useState<'PF'|'PJ'|null>(null),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');if(f.get('senha')!==f.get('confirmacao')){setError('As senhas não coincidem.');return;}setBusy(true);const body:Record<string,FormDataEntryValue|null>={nome:f.get('nome'),email:f.get('email'),senha:f.get('senha'),celular:f.get('celular')};if(tipo==='PF')body.cpfCnpj=String(f.get('cpf')).replace(/\D/g,'');else{body.cpf_cnpj=String(f.get('cpf')).replace(/\D/g,'');body.razaoSocial=f.get('razaoSocial');body.cnpj=String(f.get('cnpj')).replace(/\D/g,'');body.regimeTributario=f.get('regimeTributario');}try{await api(tipo==='PF'?'clientes':'contato/cadastro-pj',{method:'POST',body:JSON.stringify(body)});setDone(true);}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <main className="core-auth"><section className="core-auth-left"><Link href="/" aria-label="Voltar ao início"><Brand/></Link><div className="core-auth-card">{done?<><CheckCircle2 size={70} className="core-success"/><h1>Cadastro realizado!</h1><p>Sua conta foi criada com sucesso.</p><Link className="core-button" href="/login">Continuar para login</Link></>:!tipo?<><h1>Criar sua conta</h1><p>Selecione o tipo de conta que deseja criar.</p><div className="core-choice"><a href="#pf" onClick={e=>{e.preventDefault();setTipo('PF')}}><UserRound size={32}/><strong>Pessoa Física</strong><small>Para você</small><span>Continuar →</span></a><a href="#pj" onClick={e=>{e.preventDefault();setTipo('PJ')}}><Building2 size={32}/><strong>Pessoa Jurídica</strong><small>Para sua empresa</small><span>Continuar →</span></a></div><div className="core-auth-links"><Link href="/login">Já tenho uma conta</Link></div></>:<><button type="button" aria-label="Voltar à escolha do perfil" onClick={()=>{setTipo(null);setError('')}}><ArrowLeft size={19}/></button><h1>Criar sua conta {tipo==='PF'?'Pessoa Física':'Pessoa Jurídica'}</h1><form className="core-form" onSubmit={submit}><label>{tipo==='PJ'?'Nome do responsável':'Nome completo'}<input name="nome" autoComplete="name" required minLength={2} maxLength={100}/></label><label>E-mail<input name="email" type="email" autoComplete="email" required maxLength={100}/></label><label>{tipo==='PJ'?'CPF do responsável':'CPF'}<input name="cpf" inputMode="numeric" required maxLength={14} placeholder="000.000.000-00"/></label><label>Celular<input name="celular" type="tel" autoComplete="tel" maxLength={20}/></label>{tipo==='PJ'&&<><label>Razão social<input name="razaoSocial" required minLength={2} maxLength={150}/></label><label>CNPJ<input name="cnpj" inputMode="numeric" required maxLength={18} placeholder="00.000.000/0000-00"/></label><label>Regime tributário<select name="regimeTributario"><option value="simples_nacional">Simples Nacional</option><option value="mei">MEI</option><option value="lucro_presumido">Lucro Presumido</option><option value="lucro_real">Lucro Real</option></select></label></>}<label>Senha<input name="senha" type="password" autoComplete="new-password" required minLength={8} maxLength={72} placeholder="No mínimo 8 caracteres"/></label><label>Confirmar senha<input name="confirmacao" type="password" autoComplete="new-password" required minLength={8} maxLength={72}/></label>{error&&<p role="alert" className="core-alert">{error}</p>}<button className="core-button" disabled={busy}>{busy?'Criando conta…':'Criar conta'}</button></form><div className="core-auth-links"><Link href="/login">Já tenho uma conta</Link></div></>}</div></section><div className="core-auth-photo" role="img" aria-label="Profissional de contabilidade trabalhando no escritório"/></main>
}
