'use client';
import {use,useEffect,useState} from 'react';
import Link from 'next/link';
import CoreShell from '../../../components/CoreShell';
import {api,Perfil,message} from '../../../lib/core';
export default function Page({params}:{params:Promise<{id:string}>}){const {id}=use(params);return <CoreShell admin><Editor id={id}/></CoreShell>}
function Editor({id}:{id:string}){const [user,setUser]=useState<Perfil|null>(null),[empresaId,setEmpresaId]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{api<Perfil>(`admin/usuarios/${id}`).then(u=>{setUser(u);setEmpresaId(String(u.empresas[0]?.id??''));}).catch(e=>setError(message(e)));},[id]);const empresa=user?.empresas.find(e=>String(e.id)===empresaId);
async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const f=new FormData(e.currentTarget),body:Record<string,unknown>={nome:f.get('nome'),email:f.get('email'),cpfCnpj:String(f.get('cpfCnpj')).replace(/\D/g,''),celular:f.get('celular')};if(empresa){body.empresaId=empresa.id;for(const k of ['razaoSocial','nomeFantasia','cnpj','regimeTributario'])body[k]=f.get(k);body.cnpj=String(body.cnpj).replace(/\D/g,'');}try{setUser(await api<Perfil>(`admin/usuarios/${id}`,{method:'PATCH',body:JSON.stringify(body)}));setNotice('Perfil atualizado com sucesso.');}catch(e){setError(message(e))}finally{setBusy(false)}}
return <><div className="core-heading"><div><h1>Editar perfil {user?.tipo}</h1><p>Dados do cliente e das empresas vinculadas.</p></div><Link href="/admin/usuarios" className="core-button secondary">Voltar</Link></div>{error&&<p className="core-alert" role="alert">{error}</p>}{notice&&<p className="core-notice" role="status">{notice}</p>}{user?<form className="core-panel core-editor core-form" onSubmit={save}><h2>Dados do responsável</h2><div className="core-form-grid"><label>Nome<input name="nome" defaultValue={user.nome} required minLength={2} maxLength={100}/></label><label>E-mail<input name="email" type="email" defaultValue={user.email} required maxLength={100}/></label><label>CPF<input name="cpfCnpj" defaultValue={user.cpfCnpj??''} required maxLength={14}/></label><label>Celular<input name="celular" defaultValue={user.celular??''} maxLength={20}/></label></div>{!!user.empresas.length&&<><h2>Empresa</h2><label>Empresa que será editada<select value={empresaId} onChange={e=>setEmpresaId(e.target.value)}>{user.empresas.map(e=><option key={e.id} value={e.id}>{e.razaoSocial} — {e.cnpj}</option>)}</select></label>{empresa&&<div className="core-form-grid" key={empresa.id}><label>Razão social<input name="razaoSocial" defaultValue={empresa.razaoSocial} required minLength={2} maxLength={150}/></label><label>Nome fantasia<input name="nomeFantasia" defaultValue={empresa.nomeFantasia??''} maxLength={150}/></label><label>CNPJ<input name="cnpj" defaultValue={empresa.cnpj} required maxLength={18}/></label><label>Regime tributário<select name="regimeTributario" defaultValue={empresa.regimeTributario}><option value="mei">MEI</option><option value="simples_nacional">Simples Nacional</option><option value="lucro_presumido">Lucro Presumido</option><option value="lucro_real">Lucro Real</option></select></label></div>}</>}<footer><button className="core-button" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></footer></form>:!error&&<p role="status">Carregando perfil…</p>}</>}
