name: Validar Código (CI)

on:
  pull_request:
    branches:
      - main
      - develop
      - '*-short-release-*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar Lint
        run: npm run lint

      - name: Executar Build
        run: npm run build